// English walkthrough string -> Bahasa Malaysia. Product i18n wording wherever the
// product already has the string; checked by tools/walkthrough_strings.mjs --check.
export const bm: Record<string, string> = {
 "% match": "% sepadan",
 ".my": ".my",
 "1 Jan 2024": "1 Jan 2024",
 "1 Mar 2026": "1 Mac 2026",
 "1 credit": "1 kredit",
 "1 credit = RM5 · cost varies by agent": "1 kredit = RM5 · kos berbeza ikut ejen",
 "15 Oct 2026": "15 Okt 2026",
 "15 days' wages × 3 years of service": "Upah 15 hari × 3 tahun perkhidmatan",
 "16 days left": "16 hari lagi",
 "1–3 days": "1–3 hari",
 "2024 Tax Relief Schedule": "Jadual Pelepasan Cukai 2024",
 "25 questions a day — free, no credit card needed": "25 soalan sehari — percuma, tiada kad kredit diperlukan",
 "28 days short": "Kurang 28 hari",
 "3 credits": "3 kredit",
 "3 credits per draft": "3 kredit setiap draf",
 "3 matching grants": "3 geran sepadan",
 "3 matching schemes": "3 skim sepadan",
 "30 Nov 2026": "30 Nov 2026",
 "31 Oct 2026": "31 Okt 2026",
 "32 days left": "32 hari lagi",
 "3–7 days": "3–7 hari",
 "5 credits": "5 kredit",
 "6 weeks' notice for 2–5 years' service": "Notis 6 minggu untuk perkhidmatan 2–5 tahun",
 "62 days left": "62 hari lagi",
 "8 credits": "8 kredit",
 "8 → 5 credits": "8 → 5 kredit",
 "< 1 day": "< 1 hari",
 "> 1 week": "> 1 minggu",
 "A": "A",
 "A PDF to show the doctor.": "PDF untuk ditunjukkan kepada doktor.",
 "A checklist, in order.": "Senarai semak, ikut urutan.",
 "A klinik kesihatan or GP can check a fever with headache. Go to A&E if it gets worse.": "Klinik kesihatan atau klinik swasta boleh memeriksa demam dengan sakit kepala. Pergi ke Unit Kecemasan jika bertambah teruk.",
 "A quiz, a score, and what to focus on next.": "Kuiz, skor, dan apa yang perlu difokuskan seterusnya.",
 "A ready-to-use compliance report — review it before you download.": "Laporan pematuhan siap pakai — semak dahulu sebelum muat turun.",
 "A running count of what's done and what's pending.": "Kiraan semasa apa yang selesai dan belum selesai.",
 "A-Level": "A-Level",
 "AI": "AI",
 "API": "API",
 "Abdomen": "Perut",
 "About Us": "Tentang Kami",
 "Academic certificates": "Sijil akademik",
 "Age, state, income, dependents, work.": "Umur, negeri, pendapatan, tanggungan, pekerjaan.",
 "Agency, amount, deadline — and the ones you nearly qualify for.": "Agensi, jumlah, tarikh akhir — dan yang hampir layak.",
 "Agents": "Ejen",
 "Agents walk you through the whole task, step by step.": "Ejen membimbing anda sepanjang tugasan, langkah demi langkah.",
 "Aid you qualify for — and why.": "Bantuan yang anda layak — dan sebabnya.",
 "Analysing information…": "Menganalisis maklumat…",
 "And a gentle reminder to verify.": "Dan peringatan mesra untuk mengesahkan.",
 "Annual": "Tahunan",
 "Annual return": "Penyata tahunan",
 "Annual revenue (yearly, RM)": "Hasil tahunan (setahun, RM)",
 "Answer a few quick questions about your visit → get a document checklist, warnings, and official references.": "Jawab beberapa soalan ringkas tentang tujuan lawatan anda → dapatkan senarai semak dokumen, amaran, dan rujukan rasmi.",
 "Apply now →": "Mohon sekarang →",
 "Ask": "Tanya",
 "Ask NakTahu": "Tanya NakTahu",
 "Ask about government": "Soal tentang kerajaan",
 "Ask anything": "Tanya apa sahaja",
 "Ask anything about the": "Tanya apa sahaja tentang",
 "Ask once. Know now.": "Tanya je. Jawapan terus.",
 "Ask right away — free, no credit card needed.": "Tanya sekarang — percuma, tiada kad kredit diperlukan.",
 "Ask your employer for the termination letter in writing": "Minta surat penamatan secara bertulis daripada majikan",
 "Ask.": "Tanya.",
 "Automation matching grant": "Geran padanan automasi",
 "BI": "BI",
 "BM": "BM",
 "BM symptom intake → KKM guidance → clinic/hospital recommendation.": "Intake simptom BM → panduan KKM → cadangan klinik/hospital.",
 "BM voice input · Pro": "Input suara BM · Pro",
 "BM · English · 中文 — typed or spoken.": "BM · English · 中文 — taip atau sebut.",
 "BM · English · 中文, all the way through.": "BM · English · 中文, dari mula hingga akhir.",
 "Bantuan Awal Persekolahan": "Bantuan Awal Persekolahan",
 "Bi-monthly": "Dwibulanan",
 "Bigger task? NakTahu spots it.": "Tugasan lebih besar? NakTahu kesan.",
 "Birth Year": "Tahun Lahir",
 "Body area, symptoms, how long, how bad.": "Bahagian badan, simptom, berapa lama, tahap keterukan.",
 "Book a Free Call": "Tempah Panggilan Percuma",
 "Bumiputera-owned?": "Milik Bumiputera?",
 "Business": "Perniagaan",
 "Business & Grants": "Perniagaan & Geran",
 "Business type": "Jenis perniagaan",
 "CHECKLIST": "SENARAI SEMAK",
 "Can I claim for a disabled child?": "Boleh saya tuntut untuk anak OKU?",
 "Cash aid": "Bantuan tunai",
 "Check Assistance": "Semak Bantuan",
 "Check Eligibility": "Semak Kelayakan",
 "Check it yourself.": "Semak sendiri.",
 "Check with PERKESO": "Semak dengan PERKESO",
 "Check your EPF statement is up to date": "Pastikan penyata KWSP anda terkini",
 "Chest": "Dada",
 "Civic & Education": "Awam & Pendidikan",
 "Claim it when you file your income tax return on MyTax (e-Filing), under the child relief section.": "Tuntut semasa mengisi borang cukai pendapatan di MyTax (e-Filing), di bahagian pelepasan anak.",
 "Clear guidance, grounded in KKM advice.": "Panduan jelas, berdasarkan nasihat KKM.",
 "Closes 15 Jan 2027": "Tutup 15 Jan 2027",
 "Closes 30 Nov 2026": "Tutup 30 Nov 2026",
 "Commercialisation fund": "Dana pengkomersialan",
 "Compliance Checklist": "Senarai Semak Pematuhan",
 "Compliance Drafter": "Pengarang Pematuhan",
 "Comply.": "Patuhi.",
 "Confidence: 92%": "Keyakinan: 92%",
 "Confirm & Generate File": "Sahkan & Jana Fail",
 "Confirm, and the file is ready.": "Sahkan, dan fail siap.",
 "Connect": "Sambung",
 "Consultancy": "Perundingan",
 "Continue": "Teruskan",
 "Copied to clipboard": "Disalin ke papan klip",
 "Copy": "Salin",
 "Copy link": "Salin pautan",
 "Copy link, WhatsApp, Telegram, Facebook — or draft a caption with AI.": "Salin pautan, WhatsApp, Telegram, Facebook — atau jana kapsyen dengan AI.",
 "Correct · 7": "Betul · 7",
 "Cough": "Batuk",
 "Counts down for you": "Kira detik untuk anda",
 "Cradle": "Cradle",
 "Cross-references LHDN, EPF/SOCSO/EIS, and SSM compliance obligations for your SME.": "Rentas semak kewajipan LHDN, EPF/SOCSO/EIS, dan SSM untuk PKS anda.",
 "DOCUMENT CHECKLIST": "SENARAI SEMAK DOKUMEN",
 "Deadline Monitor": "Pemantau Tarikh Akhir",
 "Deadlines": "Tarikh Akhir",
 "Deadlines that come to you.": "Tarikh akhir yang datang kepada anda.",
 "Deduct monthly PCB (MTD) for every employee": "Potong PCB (MTD) bulanan bagi setiap pekerja",
 "Demographics": "Demografi",
 "Dependent children": "Tanggungan kanak-kanak",
 "Describe what happened, in one line.": "Terangkan apa yang berlaku, dalam satu ayat.",
 "Describe your business like you'd tell a friend.": "Terangkan perniagaan anda seperti bercerita kepada kawan.",
 "Digital adoption grant": "Geran pendigitalan",
 "Digital adoption grant (MDEC)": "Geran pendigitalan (MDEC)",
 "Director's MyKad copy": "Salinan MyKad pengarah",
 "Dizziness": "Pening",
 "Do you already have a job offer from a Malaysian employer?": "Adakah anda sudah menerima tawaran kerja daripada majikan Malaysia?",
 "Document checklist, warnings, and official references.": "Senarai semak dokumen, amaran, dan rujukan rasmi.",
 "Done": "Selesai",
 "Download draft": "Muat turun draf",
 "Download summary (PDF)": "Muat turun ringkasan (PDF)",
 "Draft Ready": "Draf Sedia",
 "Draft a caption (AI)": "Jana kapsyen (AI)",
 "Draft an executive summary, use-of-funds narrative, and document checklist for your selected grant.": "Draf ringkasan eksekutif, naratif penggunaan dana, dan senarai semak dokumen untuk geran pilihan anda.",
 "Draft application →": "Draf permohonan →",
 "Draft it": "Drafkan",
 "Draft.": "Draf.",
 "Drafting response…": "Mendraf jawapan…",
 "Drop in a past paper.": "Masukkan kertas soalan lepas.",
 "Drop your past paper here": "Letak kertas soalan lepas di sini",
 "EIS Claim Eligibility": "Kelayakan Tuntutan EIS",
 "EIS claim eligibility, statutory termination benefits, and a next-steps checklist.": "Kelayakan tuntutan EIS, faedah penamatan statutori, dan senarai semak langkah seterusnya.",
 "EIS claim eligibility, termination benefits, next steps.": "Kelayakan tuntutan EIS, faedah penamatan, langkah seterusnya.",
 "EIS claim — how long?": "tuntutan EIS — berapa lama?",
 "EN": "EN",
 "EPF contribution": "Caruman KWSP",
 "EPF contribution — 15th": "Caruman KWSP — 15hb",
 "EPF withdrawal": "Pengeluaran KWSP",
 "EPF withdrawal for a home": "Pengeluaran KWSP untuk rumah",
 "EPF, PERKESO, LHDN, Customs, SSM — with the official source.": "KWSP, PERKESO, LHDN, Kastam, SSM — dengan sumber rasmi.",
 "EXECUTIVE SUMMARY": "RINGKASAN EKSEKUTIF",
 "Each match says why you qualify, and links the official source.": "Setiap padanan menyatakan sebab anda layak, dengan pautan ke sumber rasmi.",
 "Each number is a source you can open.": "Setiap nombor ialah sumber yang boleh dibuka.",
 "Earlier": "Sebelum ini",
 "EdTech": "EdTech",
 "Education": "Pendidikan",
 "Emergencies come first": "Kecemasan diutamakan",
 "Employer's job offer letter": "Surat tawaran kerja majikan",
 "Employment": "Pekerjaan",
 "Employment Pass": "Pas Pekerjaan",
 "End card": "End card",
 "Enrol foreign workers with SOCSO": "Daftarkan pekerja asing dengan PERKESO",
 "Enter to send · Ctrl+Enter · Esc to clear": "Enter untuk hantar · Ctrl+Enter · Esc untuk padam",
 "Essentials credit": "Kredit barangan asas",
 "Estimated Statutory Termination Benefit": "Anggaran Faedah Penamatan Statutori",
 "Every claim is numbered.": "Setiap fakta bernombor.",
 "Every claim, linked to its official source.": "Setiap fakta, dipautkan ke sumber rasminya.",
 "Every filing date, in one calendar.": "Setiap tarikh pemfailan, dalam satu kalendar.",
 "Every grant you qualify for, ranked.": "Setiap geran yang anda layak, disusun mengikut kedudukan.",
 "Every obligation, in one checklist.": "Setiap kewajipan, dalam satu senarai semak.",
 "Every question, explained.": "Setiap soalan, dijelaskan.",
 "Every scheme you match, in one list.": "Setiap skim yang sepadan, dalam satu senarai.",
 "Everything you asked, saved.": "Semua soalan anda, disimpan.",
 "Executive summary, use of funds, document checklist.": "Ringkasan eksekutif, penggunaan dana, senarai semak dokumen.",
 "Explain": "Penjelasan",
 "Explanations": "Penjelasan",
 "Explore AI Agents": "Terokai Ejen AI",
 "Export Format": "Format Eksport",
 "Extend My Visa": "Lanjutkan Visa",
 "Extract & explain": "Ekstrak & jelaskan",
 "FREE": "PERCUMA",
 "FREE CIVIC TOOLS": "ALAT AWAM PERCUMA",
 "Fan-out across up to 13 domains, merged into one synthesis.": "Carian selari merentas sehingga 13 domain, digabungkan menjadi satu sintesis.",
 "Feeling unwell": "Rasa tidak sihat",
 "Fever": "Demam",
 "File the annual return on time": "Failkan penyata tahunan tepat pada masanya",
 "File your EIS claim with PERKESO": "Failkan tuntutan EIS anda dengan PERKESO",
 "Financial Projection · Template only — not real figures": "Unjuran Kewangan · Templat sahaja — bukan angka sebenar",
 "Find grants": "Cari geran",
 "Find.": "Cari.",
 "Fintech": "Fintech",
 "Five quick answers about your business.": "Lima jawapan ringkas tentang perniagaan anda.",
 "Focus next:": "Fokus seterusnya:",
 "Follow-ups, history, and the right agent.": "Soalan susulan, sejarah, dan ejen yang tepat.",
 "Form": "Borang",
 "Found one? Draft the application.": "Jumpa satu? Drafkan permohonan.",
 "Free": "Percuma",
 "Free Text": "Teks Bebas",
 "Free.": "Percuma.",
 "From match to application, reviewed by you.": "Dari padanan ke permohonan, disemak oleh anda.",
 "General": "Umum",
 "Generate Draft": "Jana Draf",
 "Generate checklist": "Jana senarai semak",
 "Generate quiz": "Jana kuiz",
 "Get directions": "Dapatkan arah",
 "Get guidance": "Dapatkan panduan",
 "Go deeper": "Lebih mendalam",
 "Google Calendar": "Google Calendar",
 "Google or Microsoft, with alerts before each deadline.": "Google atau Microsoft, dengan makluman sebelum setiap tarikh akhir.",
 "Grant & Business Details": "Butiran Geran & Perniagaan",
 "Grant Draft": "Draf Geran",
 "Grant Draft Generator": "Penjana Draf Geran",
 "Grant Finder": "Pencari Geran",
 "Grant Finder matches your business to government grants.": "Pencari Geran memadankan perniagaan anda dengan geran kerajaan.",
 "Grants I qualify for": "geran yang saya layak",
 "Grants, filings, deadlines — handled.": "Geran, pemfailan, tarikh akhir — beres.",
 "Grounded in Malaysian government sources, not the open web.": "Berdasarkan sumber kerajaan Malaysia, bukan internet terbuka.",
 "Grounded.": "Bersumber.",
 "Guided.": "Dibimbing.",
 "Hardware": "Perkakasan",
 "Head": "Kepala",
 "Headache": "Sakit kepala",
 "Health Triage": "Triaj Kesihatan",
 "Health Triage, Check Assistance, Retrenchment Navigator": "Triaj Kesihatan, Semak Bantuan, Navigator Pemberhentian Kerja",
 "Help / FAQ": "Bantuan / FAQ",
 "Here's your visa type and document checklist.": "Berikut adalah jenis visa dan senarai semak dokumen anda.",
 "History": "History",
 "Home": "Beranda",
 "Hook": "Hook",
 "Household": "Isi Rumah",
 "Household income (RM)": "Pendapatan isi rumah (RM)",
 "Household income and children within the STR bands": "Pendapatan isi rumah dan bilangan anak dalam kategori STR",
 "How bad?": "Seteruk mana?",
 "How do I claim child tax relief?": "Bagaimana cara mohon pelepasan cukai anak?",
 "How do I register a company with SSM?": "Bagaimana cara daftar syarikat dengan SSM?",
 "How long?": "Berapa lama?",
 "How to pay taxes": "Cara bayar cukai",
 "I need more details": "Saya perlukan butiran lanjut",
 "I worked 3 years, salary RM4,500, given 14 days notice": "Saya bekerja 3 tahun, gaji RM4,500, diberi notis 14 hari",
 "I worked 3 years, salary RM4,500, given 14 days notice…": "Saya bekerja 3 tahun, gaji RM4,500, diberi notis 14 hari…",
 "I'm from Mainland China, want to work in KL for 2 years": "Saya dari China Tanah Besar, mahu bekerja di KL selama 2 tahun",
 "ILLUSTRATIVE DEMO DATA": "DATA DEMO ILUSTRASI",
 "If you contributed to EIS, claim within 60 days": "Jika anda mencarum EIS, tuntut dalam tempoh 60 hari",
 "Immigration": "Imigresen",
 "Immigration & Documents": "Imigresen & Dokumen",
 "Immigration Navigator": "Navigator Imigresen",
 "In effect from 1 Jan 2024": "Berkuat kuasa mulai 1 Jan 2024",
 "In plain language, with quick replies.": "Dalam bahasa mudah, dengan balasan pantas.",
 "It asks what matters, one step at a time.": "Ia bertanya perkara penting, satu langkah demi satu.",
 "It searches before it speaks.": "Ia mencari dahulu sebelum menjawab.",
 "It suggests the specialised agent built for the job.": "Ia mencadangkan ejen khusus untuk tugasan itu.",
 "JPN": "JPN",
 "Jawapan: pengaruh pendidikan dan akhbar, serta kesan Perang Dunia Kedua. Kata kunci: kesedaran, penentangan.": "Jawapan: pengaruh pendidikan dan akhbar, serta kesan Perang Dunia Kedua. Kata kunci: kesedaran, penentangan.",
 "Just ask.": "Tanya je.",
 "KKM": "KKM",
 "KPM": "KPM",
 "KWSP": "KWSP",
 "KWSP — i-Akaun": "KWSP — i-Akaun",
 "Keep birth certificates and enrolment letters in case LHDN asks.": "Simpan sijil kelahiran dan surat pendaftaran sekiranya LHDN meminta.",
 "Keep company particulars up to date": "Pastikan butiran syarikat sentiasa terkini",
 "Keep your child's birth certificate, plus proof of enrolment for any child in higher education. LHDN can ask for them for up to 7 years.": "Simpan sijil kelahiran anak anda, serta bukti pendaftaran bagi anak di pengajian tinggi. LHDN boleh memintanya sehingga 7 tahun.",
 "Kemerdekaan": "Kemerdekaan",
 "Klinik Kesihatan · 1.2 km": "Klinik Kesihatan · 1.2 km",
 "Klinik Kesihatan · 3.4 km": "Klinik Kesihatan · 3.4 km",
 "Knowledge base → analysis → drafting, live on screen.": "Pangkalan pengetahuan → analisis → draf, terus di skrin.",
 "LHDN": "LHDN",
 "LHDN Form E": "Borang E LHDN",
 "LHDN, EPF · SOCSO · EIS, and SSM — cross-referenced.": "LHDN, EPF · SOCSO · EIS, dan SSM — disemak silang.",
 "LHDN, EPF/SOCSO/EIS and SSM obligations for your SME.": "Kewajipan LHDN, EPF/SOCSO/EIS dan SSM untuk PKS anda.",
 "LLP": "LLP",
 "Latest audited accounts": "Akaun beraudit terkini",
 "Leave with the visa type and a checklist.": "Pulang dengan jenis visa dan senarai semak.",
 "Level": "Peringkat",
 "Life happens.": "Hidup ada pasang surutnya.",
 "Life moments": "Detik kehidupan",
 "Link copied!": "Pautan disalin!",
 "Losing a job": "Hilang kerja",
 "Lost MyKad": "MyKad hilang",
 "MANAGED SERVICE": "PERKHIDMATAN TERURUS",
 "MDEC": "MDEC",
 "MOF": "MOF",
 "Macam mana nak keluarkan KWSP untuk beli rumah?": "Macam mana nak keluarkan KWSP untuk beli rumah?",
 "Making ends meet": "Menampung sara hidup",
 "Malaysian government.": "kerajaan Malaysia.",
 "Manufacturing": "Pembuatan",
 "Many agents are free; others cost 1–3 credits a run.": "Banyak ejen percuma; yang lain 1–3 kredit setiap penggunaan.",
 "Marital Status": "Taraf Perkahwinan",
 "Married": "Berkahwin",
 "Match your business profile to Malaysian government grants — with scoring, near-miss detection, and a recommended application sequence.": "Padankan profil perniagaan anda dengan geran kerajaan Malaysia — dengan skor kelayakan, pengesanan hampir-layak, dan urutan permohonan disyorkan.",
 "Match your household profile to cost-of-living assistance schemes (Ihsan MADANI and similar).": "Padankan profil isi rumah anda dengan skim bantuan sara hidup kerajaan (Ihsan MADANI dan seumpamanya).",
 "Match your household to cost-of-living assistance schemes.": "Padankan isi rumah anda dengan skim bantuan sara hidup.",
 "Match your profile to government grants (MDEC, TEKUN, MARA…).": "Padankan profil anda dengan geran kerajaan (MDEC, TEKUN, MARA…).",
 "Matching…": "Memadankan…",
 "Matematik": "Matematik",
 "Microsoft Calendar": "Microsoft Calendar",
 "Mode": "Mod",
 "Monthly": "Bulanan",
 "Months registered": "Bulan berdaftar",
 "Moving here": "Berpindah ke sini",
 "MyTax — login": "MyTax — log masuk",
 "NEARBY FACILITIES": "KEMUDAHAN BERDEKATAN",
 "NakTahu Agents": "Ejen NakTahu",
 "Nasionalisme": "Nasionalisme",
 "Nausea / Vomiting": "Loya / Muntah",
 "Near-miss — close, but doesn't fully qualify yet ·": "Hampir layak — dekat, tetapi belum layak sepenuhnya ·",
 "Near-miss: what you'd need": "Hampir layak: apa yang diperlukan",
 "Never a mystery why.": "Sebabnya sentiasa jelas.",
 "Never miss one": "Jangan terlepas lagi",
 "New": "Baharu",
 "No": "Tidak",
 "No account needed to read a shared answer.": "Tiada akaun diperlukan untuk membaca jawapan yang dikongsi.",
 "No keywords, no forms.": "Tiada kata kunci, tiada borang.",
 "Not quite · 1": "Tidak tepat · 1",
 "Not the paperwork.": "Bukan kertas kerja.",
 "Nothing is generated until you approve the draft.": "Tiada apa dijana sehingga anda luluskan draf.",
 "Notice Period Status": "Status Tempoh Notis",
 "One click hands it to the Grant Draft Generator.": "Satu klik menyerahkannya kepada Penjana Draf Geran.",
 "One tap asks the next obvious question.": "Satu ketik untuk soalan seterusnya.",
 "Open Official Portal": "Buka Portal Rasmi",
 "Open →": "Buka →",
 "Or just say it.": "Atau sebut sahaja.",
 "Or use the form — headcount, revenue, recent events.": "Atau guna borang — bilangan pekerja, hasil, peristiwa terkini.",
 "Our company, a Kuala Lumpur Sdn Bhd registered for 18 months, is applying to digitise its order-to-invoice workflow. The grant will fund cloud software, staff training and a small hardware refresh, cutting manual processing time and letting the team serve more SME customers across the Klang Valley. The project runs for 12 months with quarterly milestones reported to the agency.": "Syarikat kami, sebuah Sdn Bhd di Kuala Lumpur yang berdaftar selama 18 bulan, memohon untuk mendigitalkan aliran kerja pesanan-ke-invois. Geran ini akan membiayai perisian awan, latihan kakitangan dan penambahbaikan kecil perkakasan, sekali gus mengurangkan masa pemprosesan manual dan membolehkan pasukan melayani lebih ramai pelanggan PKS di seluruh Lembah Klang. Projek ini berjalan selama 12 bulan dengan pencapaian suku tahunan dilaporkan kepada agensi.",
 "PCB (MTD) remittance": "Remitan PCB (MTD)",
 "PCB table 2026 (PDF)": "Jadual PCB 2026 (PDF)",
 "PDF": "PDF",
 "PERKESO": "PERKESO",
 "PRO — BUSINESS": "PRO — PERNIAGAAN",
 "PTPTN education loan": "Pinjaman pendidikan PTPTN",
 "PVIP": "PVIP",
 "Paperwork follows.": "Kertas kerja menyusul.",
 "Partially correct · 2": "Separuh betul · 2",
 "Passport photo": "Gambar pasport",
 "Passport with enough validity": "Pasport dengan tempoh sah mencukupi",
 "Past papers, explained. Then tested.": "Kertas lepas, dijelaskan. Kemudian diuji.",
 "Paste it, upload the PDF, or scan a photo.": "Tampal, muat naik PDF, atau imbas foto.",
 "Paste text": "Tampal teks",
 "PatuhiKu": "PatuhiKu",
 "Pay monthly EIS contributions": "Bayar caruman EIS bulanan",
 "Pay per use — or not at all.": "Bayar ikut penggunaan — atau langsung tidak.",
 "Pelepasan bergantung pada umur dan pengajian anak — sehingga RM8,000 setahun bagi setiap anak di pengajian tinggi, tertakluk kepada syarat semasa LHDN.": "Pelepasan bergantung pada umur dan pengajian anak — sehingga RM8,000 setahun bagi setiap anak di pengajian tinggi, tertakluk kepada syarat semasa LHDN.",
 "Pending": "Belum Selesai",
 "Perniagaan Terurus: we handle your compliance and grants.": "Perniagaan Terurus: kami uruskan pematuhan dan geran anda.",
 "Persekutuan 1948": "Persekutuan 1948",
 "Pick PDF or Word, then generate.": "Pilih PDF atau Word, kemudian jana.",
 "Pick what you're trying to do.": "Pilih apa yang anda mahu lakukan.",
 "Plain words, straight to an answer.": "Bahasa mudah, terus ke jawapan.",
 "Plus official references and a ready-to-send enquiry.": "Serta rujukan rasmi dan pertanyaan sedia dihantar.",
 "Plus the nearest facilities and directions.": "Serta kemudahan terdekat dan arah ke sana.",
 "Pricing": "Harga",
 "Private sector": "Sektor swasta",
 "Pro": "Pro",
 "Property Concierge": "Concierge Hartanah",
 "QUERY HISTORY": "SEJARAH SOALAN",
 "Query history · Pro": "Sejarah soalan · Pro",
 "Query history, grouped by day.": "Sejarah soalan, dikumpul mengikut hari.",
 "Quiz": "Kuiz",
 "Quotations from vendors": "Sebut harga daripada vendor",
 "RM 150,000 – RM 500,000": "RM 150,000 – RM 500,000",
 "RM 99/mo per workspace · up to 5 staff": "RM 99/bulan setiap ruang kerja · sehingga 5 kakitangan",
 "Rather hand it all off?": "Mahu serahkan semuanya?",
 "Real gov.my source — never invented": "Sumber gov.my sebenar — tidak direka",
 "Reason shown for every match": "Sebab ditunjukkan bagi setiap padanan",
 "Recap": "Recap",
 "Recommended": "Disyorkan",
 "Regenerate response": "Jana semula jawapan",
 "Register a company with SSM": "Daftar syarikat dengan SSM",
 "Register new foreign workers for EPF contributions": "Daftarkan pekerja asing baharu untuk caruman KWSP",
 "Register to vote": "Daftar sebagai pengundi",
 "Regulatory deadline calendar with proactive alerts.": "Kalendar tarikh akhir kawal selia dengan makluman proaktif.",
 "Relief depends on your child's age and studies — up to RM8,000 a year per child in higher education, subject to current LHDN conditions.": "Pelepasan bergantung pada umur dan pengajian anak — sehingga RM8,000 setahun bagi setiap anak di pengajian tinggi, tertakluk kepada syarat semasa LHDN.",
 "Renew ePLKS": "Perbaharui ePLKS",
 "Request your final payslip and EA form": "Minta slip gaji terakhir dan borang EA",
 "Research Synthesiser": "Penyelidik Sintesis",
 "Retrenchment": "Pemberhentian kerja",
 "Retrenchment Navigator": "Navigator Pemberhentian Kerja",
 "Review Draft": "Semak Draf",
 "Rolling applications": "Permohonan berterusan",
 "Routes you to the right agent": "Bawa anda ke ejen yang tepat",
 "Run the business.": "Uruskan perniagaan.",
 "Run your business": "Urus perniagaan anda",
 "SME Corp": "SME Corp",
 "SOCSO & EIS contribution": "Caruman PERKESO & EIS",
 "SOCSO form which one": "borang perkeso yang mana satu",
 "SPM": "SPM",
 "SPM sejarah past year": "soalan tahun lepas sejarah SPM",
 "SPO Enquiry Draft": "Draf Pertanyaan SPO",
 "SSM": "SSM",
 "SSM annual return due??": "penyata tahunan SSM bila due??",
 "SSM company profile": "Profil syarikat SSM",
 "SST return": "Penyata SST",
 "SST threshold?": "had SST berapa?",
 "STPM": "STPM",
 "STR, SARA and more — with the agency that runs each one.": "STR, SARA dan banyak lagi — dengan agensi yang mengendalikannya.",
 "Sains": "Sains",
 "Same answer, same sources — just in your language.": "Jawapan sama, sumber sama — dalam bahasa anda.",
 "Scan photo": "Imbas foto",
 "Score: 8/10": "Skor: 8/10",
 "Scored against your profile": "Diskor berdasarkan profil anda",
 "Sdn Bhd": "Sdn Bhd",
 "Searching knowledge base…": "Mencari dalam pangkalan pengetahuan…",
 "Sector": "Sektor",
 "Sector, business type, age, revenue, ownership.": "Sektor, jenis perniagaan, usia, hasil, pemilikan.",
 "Sejarah": "Sejarah",
 "Selangor": "Selangor",
 "Send a verified answer in one tap.": "Hantar jawapan disahkan dengan satu ketik.",
 "Send it to the calendar you already use.": "Hantar ke kalendar yang anda sudah guna.",
 "Services": "Perkhidmatan",
 "Severe": "Teruk",
 "Share": "Kongsi",
 "Share it where people actually talk.": "Kongsi di tempat orang benar-benar berbual.",
 "Share to Facebook": "Kongsi ke Facebook",
 "Share to Telegram": "Kongsi ke Telegram",
 "Share to WhatsApp": "Kongsi ke WhatsApp",
 "Share.": "Kongsi.",
 "Shared answers always carry the official-source disclaimer.": "Jawapan dikongsi sentiasa disertakan penafian sumber rasmi.",
 "Shared from NakTahu AI. Verify important information against official sources.": "Dikongsi daripada NakTahu AI. Sahkan maklumat penting dengan sumber rasmi.",
 "Simpan sijil kelahiran dan surat pendaftaran sekiranya LHDN meminta.": "Simpan sijil kelahiran dan surat pendaftaran sekiranya LHDN meminta.",
 "Sitting SPM": "Ambil SPM",
 "Skin": "Kulit",
 "Soalan 1 · Nyatakan dua faktor kemunculan nasionalisme di Tanah Melayu.": "Soalan 1 · Nyatakan dua faktor kemunculan nasionalisme di Tanah Melayu.",
 "Soalan 2 · Apakah tujuan penubuhan Persekutuan Tanah Melayu 1948?": "Soalan 2 · Apakah tujuan penubuhan Persekutuan Tanah Melayu 1948?",
 "Soalan 3 · Terangkan peranan Suruhanjaya Reid.": "Soalan 3 · Terangkan peranan Suruhanjaya Reid.",
 "Software & cloud": "Perisian & awan",
 "Sole Proprietor": "Peniaga Tunggal",
 "Some agents use \"credits\" — each credit is RM5 and covers one full use of that agent. Business plans have no limit.": "Sesetengah ejen guna \"kredit\" — setiap kredit = RM 5 dan setara satu penggunaan penuh ejen tersebut. Pelan Perniagaan tiada had.",
 "Some questions need more than an answer.": "Sesetengah soalan perlukan lebih daripada jawapan.",
 "Speak in BM and your words become the question.": "Bercakap dalam BM dan kata-kata anda jadi soalan.",
 "Staff training": "Latihan kakitangan",
 "Start": "Mula",
 "Start Asking": "Mula Bertanya",
 "Start a Business": "Memulakan Perniagaan",
 "Start on naktahu.my.": "Mulakan di naktahu.my.",
 "Start with money on the table.": "Mulakan dengan dana yang tersedia.",
 "Startup": "Startup",
 "State of Residence": "Negeri Tempat Tinggal",
 "Status": "Status",
 "Stay compliant": "Kekal patuh",
 "Step-by-step helpers for everyday government tasks — answers grounded in official sources, not guesses.": "Pembantu langkah demi langkah untuk tugas kerajaan biasa — jawapan berdasarkan sumber rasmi, bukan agakan.",
 "Stop searching.": "Berhenti mencari.",
 "Straight to the official portal": "Terus ke portal rasmi",
 "Student": "Pelajar",
 "Study Agent": "Ejen Pelajaran",
 "Study in Malaysia": "Belajar di Malaysia",
 "Subject": "Subjek",
 "Submit Form E by 31 March": "Hantar Borang E sebelum 31 Mac",
 "Submit MDAC": "Hantar MDAC",
 "Suggested follow-ups": "Soalan susulan yang dicadangkan",
 "Suggested follow-ups keep you moving.": "Soalan susulan yang dicadangkan memudahkan anda terus bertanya.",
 "Sumbangan Asas Rahmah (SARA)": "Sumbangan Asas Rahmah (SARA)",
 "Sumbangan Tunai Rahmah (STR)": "Sumbangan Tunai Rahmah (STR)",
 "Switch the answer to Bahasa Malaysia…": "Tukar jawapan ke English…",
 "Symptom intake → KKM guidance → clinic or hospital.": "Intake simptom → panduan KKM → klinik atau hospital.",
 "Symptoms": "Simptom",
 "Sync to your calendar": "Segerak ke kalendar anda",
 "Take the summary with you.": "Bawa ringkasan bersama anda.",
 "Tap through what you're feeling.": "Ketik apa yang anda rasa.",
 "Tax & EPF": "Cukai & KWSP",
 "Tech Sdn Bhd, 8 employees, started hiring foreign workers last month, annual revenue RM800k": "Sdn Bhd teknologi, 8 pekerja, mula ambil pekerja asing bulan lepas, hasil tahunan RM800k",
 "Technology": "Teknologi",
 "Technology fund": "Dana teknologi",
 "Tell it about your household.": "Ceritakan tentang isi rumah anda.",
 "Tell me about your plans — where are you from, and how long will you stay?": "Ceritakan rancangan anda — dari mana anda berasal, dan berapa lama anda akan tinggal?",
 "Tenancy, strata and land-title answers, plus a shareable brief.": "Jawapan sewaan, strata dan hak milik tanah, serta brief sedia dikongsi.",
 "Termination benefit, notice period, and where EIS fits in.": "Faedah penamatan, tempoh notis, dan peranan EIS.",
 "The answer streams in as it's written.": "Jawapan dipaparkan sambil ditulis.",
 "The big moments, made simpler.": "Detik penting, dipermudahkan.",
 "The grant and your details carry over.": "Geran dan butiran anda dibawa terus.",
 "The right visa, and every document for it.": "Visa yang tepat, dan setiap dokumennya.",
 "Then test yourself.": "Kemudian uji diri anda.",
 "Then, what to do next.": "Kemudian, apa perlu dibuat seterusnya.",
 "They see the answer and its sources.": "Mereka nampak jawapan dan sumbernya.",
 "Tick them off as you go.": "Tandakan satu demi satu.",
 "Title": "Tajuk",
 "Today": "Hari ini",
 "Topic ·": "Topik ·",
 "Translate answer": "Terjemah jawapan",
 "Triggered by: foreign workers": "Dicetuskan oleh: pekerja asing",
 "Tuntut semasa mengisi borang cukai pendapatan di MyTax (e-Filing), di bahagian pelepasan anak.": "Tuntut semasa mengisi borang cukai pendapatan di MyTax (e-Filing), di bahagian pelepasan anak.",
 "Twelve specialists for the paperwork of life.": "Dua belas pakar untuk urusan dokumen kehidupan.",
 "Type your answer…": "Taip jawapan anda…",
 "Type your question in plain words.": "Taip soalan anda dalam bahasa mudah.",
 "USE OF FUNDS": "PENGGUNAAN DANA",
 "Up to RM 100,000": "Sehingga RM 100,000",
 "Up to RM 50,000": "Sehingga RM 50,000",
 "Upload PDF": "Muat naik PDF",
 "Upload your SPM past paper — an explanation for every question.": "Muat naik kertas SPM anda — penjelasan untuk setiap soalan.",
 "Upload your SPM past paper — get an explanation for every question and see which topics to focus on.": "Muat naik kertas SPM anda — dapatkan penjelasan setiap soalan dan topik mana perlu diberi tumpuan.",
 "Verified 12 Sep 2026": "Disahkan 12 Sep 2026",
 "Verify": "Sahkan",
 "Verify.": "Sahkan.",
 "View official source ↗": "Lihat sumber rasmi ↗",
 "Visit": "Melawat",
 "Voice input": "Input suara",
 "WALKTHROUGH": "PANDUAN",
 "WALKTHROUGH 01 · ASK ANYTHING": "PANDUAN 01 · TANYA APA SAHAJA",
 "WALKTHROUGH 02 · RUN YOUR BUSINESS": "PANDUAN 02 · URUS PERNIAGAAN ANDA",
 "WALKTHROUGH 03 · LIFE MOMENTS": "PANDUAN 03 · DETIK KEHIDUPAN",
 "Warung Watch": "Warung Watch",
 "We Handle Your Compliance & Grants": "Kami Uruskan Pematuhan & Geran Anda",
 "What do you need to know today?": "Apa yang anda perlu tahu hari ini?",
 "What documents do I need?": "Dokumen apa yang saya perlukan?",
 "What you're owed, and what to do next.": "Hak anda, dan apa perlu dibuat seterusnya.",
 "What you're owed, worked out.": "Hak anda, siap dikira.",
 "When is the e-Filing deadline?": "Bila tarikh akhir e-Filing?",
 "When it took effect, how confident the match is, and the official page.": "Bila ia berkuat kuasa, tahap keyakinan padanan, dan halaman rasmi.",
 "Where do you feel it?": "Di mana anda rasa?",
 "Where to go, and how soon.": "Ke mana perlu pergi, dan bila.",
 "Which documents should I keep?": "Dokumen apa yang perlu saya simpan?",
 "Why you qualify ·": "Sebab layak ·",
 "With the topic it tests, so you know what to revise.": "Dengan topik yang diuji, supaya anda tahu apa perlu diulang kaji.",
 "Work in Malaysia": "Bekerja di Malaysia",
 "Work, study, visit, start a business, extend a visa…": "Bekerja, belajar, melawat, mulakan perniagaan, lanjutkan visa…",
 "Years of service, salary, notice given.": "Tempoh berkhidmat, gaji, notis diberi.",
 "Yes": "Ya",
 "You have school-age children": "Anda mempunyai anak usia sekolah",
 "You review every section first.": "Anda semak setiap bahagian dahulu.",
 "You're already an STR household": "Isi rumah anda sudah menerima STR",
 "Your language": "Bahasa anda",
 "Your obligations, grouped by agency.": "Kewajipan anda, dikumpul mengikut agensi.",
 "Your postcode (e.g. 50450)": "Poskod anda (cth. 50450)",
 "Your profile, matched and ranked.": "Profil anda, dipadankan dan disusun.",
 "am I eligible for STR?": "saya layak STR ke?",
 "blog: 10 reliefs you missed": "blog: 10 pelepasan cukai yang anda terlepas",
 "currentColor": "currentColor",
 "e-Filing (MyTax) guide": "Panduan e-Filing (MyTax)",
 "e-Filing guide (PDF, 84 pages)": "Panduan e-Filing (PDF, 84 muka surat)",
 "e.g. 18": "cth. 18",
 "e.g. 250000": "cth. 250000",
 "e.g. Tech Sdn Bhd, 8 employees, started hiring foreign workers last month…": "cth: Sdn Bhd teknologi, 8 pekerja, mula ambil pekerja asing bulan lepas…",
 "foreign worker EPF rules": "peraturan kwsp pekerja asing",
 "forum: child relief 2024??": "forum: pelepasan anak 2024??",
 "grant FAQ — page 3 of 9": "Soalan lazim geran — muka 3 daripada 9",
 "grants_list_v7_FINAL.xlsx": "grants_list_v7_FINAL.xlsx",
 "hasil.gov.my": "hasil.gov.my",
 "hasil.gov.my — Tax relief": "hasil.gov.my — Pelepasan cukai",
 "klinik near me open now": "klinik berdekatan buka sekarang",
 "lost MyKad what to do": "mykad hilang apa perlu buat",
 "naktahu.my": "naktahu.my",
 "needs 24 months registered": "perlu 24 bulan berdaftar",
 "news: budget tax changes": "berita: perubahan cukai bajet",
 "of 7 done": "daripada 7 selesai",
 "retrenchment benefit calculator": "kalkulator faedah diberhentikan kerja",
 "thread: is it RM2k or RM8k?": "thread: RM2k ke RM8k?",
 "work visa malaysia 2026": "visa kerja malaysia 2026",
 "{agent}": "{agent}",
 "· View official source ↗": "· Lihat sumber rasmi ↗",
 "— revise the Reid Commission.": "— ulang kaji Suruhanjaya Reid.",
 "…or 中文, in one click.": "…atau 中文, dengan satu klik.",
 "≈ RM 7,788": "≈ RM 7,788",
 "● Bilingual engine active": "● Enjin dwibahasa aktif",
 "● gov.my sources verified": "● Sumber gov.my disahkan",
 "✓ Connected": "✓ Disambungkan",
 "✦ This looks like a {agent} question": "✦ Ini kelihatan seperti soalan untuk {agent}",
 "减免额视孩子的年龄与学业而定——每名就读高等教育的孩子每年最高可获RM8,000，须符合LHDN现行条件。": "减免额视孩子的年龄与学业而定——每名就读高等教育的孩子每年最高可获RM8,000，须符合LHDN现行条件。",
 "在MyTax（e-Filing）申报所得税时，于子女减免一栏申请。": "在MyTax（e-Filing）申报所得税时，于子女减免一栏申请。",
 "请保存出生证明与入学信，以备LHDN查核。": "请保存出生证明与入学信，以备LHDN查核。",
 "🇲🇾 Built for Malaysia": "🇲🇾 Dibuat untuk Malaysia",
 "🔒 naktahu.my/a/k7Q2mX": "🔒 naktahu.my/a/k7Q2mX",
 "🚨 Emergency? Call 999 now": "🚨 Kecemasan? Hubungi 999 sekarang",
 "🟡 Moderate": "🟡 Sederhana",
 "🟡 See a doctor within 24 hours": "🟡 Jumpa doktor dalam tempoh 24 jam",
 "🟢 Mild": "🟢 Ringan"
};
