// English walkthrough string -> Simplified Chinese. Product i18n wording wherever the
// product already has the string; checked by tools/walkthrough_strings.mjs --check.
export const zh: Record<string, string> = {
 "% match": "% 匹配",
 ".my": ".my",
 "1 Jan 2024": "2024年1月1日",
 "1 Mar 2026": "2026年3月1日",
 "1 credit": "1 点数",
 "1 credit = RM5 · cost varies by agent": "1 点数 = RM5 · 各代理收费不同",
 "15 Oct 2026": "2026年10月15日",
 "15 days' wages × 3 years of service": "15 天工资 × 3 年服务",
 "16 days left": "16 天后",
 "1–3 days": "1–3 天",
 "2024 Tax Relief Schedule": "2024 年税务减免表",
 "25 questions a day — free, no credit card needed": "每日 25 次查询 — 完全免费，无需信用卡",
 "28 days short": "短缺 28 天",
 "3 credits": "3 点数",
 "3 credits per draft": "每份草稿 3 点数",
 "3 matching grants": "3 项匹配资助",
 "3 matching schemes": "3 项匹配援助计划",
 "30 Nov 2026": "2026年11月30日",
 "31 Oct 2026": "2026年10月31日",
 "32 days left": "32 天后",
 "3–7 days": "3–7 天",
 "5 credits": "5 点数",
 "6 weeks' notice for 2–5 years' service": "服务 2–5 年须给 6 周通知",
 "62 days left": "62 天后",
 "8 credits": "8 点数",
 "8 → 5 credits": "8 → 5 点数",
 "< 1 day": "< 1 天",
 "> 1 week": "> 1 周",
 "A": "A",
 "A PDF to show the doctor.": "一份可以给医生看的 PDF。",
 "A checklist, in order.": "一份按顺序排列的清单。",
 "A klinik kesihatan or GP can check a fever with headache. Go to A&E if it gets worse.": "发烧伴随头痛，可到 Klinik Kesihatan 或私人诊所（GP）检查。如情况恶化，请前往急诊室（A&E）。",
 "A quiz, a score, and what to focus on next.": "测验、得分，以及下一步该重点复习什么。",
 "A ready-to-use compliance report — review it before you download.": "可直接使用的合规报告 — 下载前可先审阅。",
 "A running count of what's done and what's pending.": "已完成与待处理事项，一目了然。",
 "A-Level": "A-Level",
 "AI": "AI",
 "API": "API",
 "Abdomen": "腹部",
 "About Us": "关于我们",
 "Academic certificates": "学历证书",
 "Age, state, income, dependents, work.": "年龄、州属、收入、受养人、工作。",
 "Agency, amount, deadline — and the ones you nearly qualify for.": "负责机构、金额、截止日期 — 还有差一点就符合资格的资助。",
 "Agents": "智能代理",
 "Agents walk you through the whole task, step by step.": "智能代理一步步带您完成整项任务。",
 "Aid you qualify for — and why.": "您符合资格的援助 — 以及原因。",
 "Analysing information…": "正在分析信息…",
 "And a gentle reminder to verify.": "并温馨提醒您自行核实。",
 "Annual": "每年",
 "Annual return": "年度申报表",
 "Annual revenue (yearly, RM)": "年收入（每年，RM）",
 "Answer a few quick questions about your visit → get a document checklist, warnings, and official references.": "回答几个关于您行程的简单问题 → 获取文件清单、注意事项及官方参考资料。",
 "Apply now →": "立即申请 →",
 "Ask": "提问",
 "Ask NakTahu": "问问 NakTahu",
 "Ask about government": "询问政府事务",
 "Ask anything": "有问必答",
 "Ask anything about the": "为您解答关于",
 "Ask once. Know now.": "问一次，马上知道。",
 "Ask right away — free, no credit card needed.": "立即提问 — 免费，无需信用卡。",
 "Ask your employer for the termination letter in writing": "要求雇主提供书面终止雇佣信",
 "Ask.": "提问。",
 "Automation matching grant": "自动化配对补助金",
 "BI": "BI",
 "BM": "BM",
 "BM symptom intake → KKM guidance → clinic/hospital recommendation.": "BM 症状问诊 → KKM 指引 → 诊所/医院建议。",
 "BM voice input · Pro": "BM 语音输入 · Pro",
 "BM · English · 中文 — typed or spoken.": "BM · English · 中文 — 打字或说话皆可。",
 "BM · English · 中文, all the way through.": "BM · English · 中文，全程通用。",
 "Bantuan Awal Persekolahan": "Bantuan Awal Persekolahan",
 "Bi-monthly": "每两个月",
 "Bigger task? NakTahu spots it.": "任务更复杂？NakTahu 一眼看出。",
 "Birth Year": "出生年份",
 "Body area, symptoms, how long, how bad.": "身体部位、症状、持续多久、严重程度。",
 "Book a Free Call": "预约免费通话",
 "Bumiputera-owned?": "是否为土著（Bumiputera）所拥有？",
 "Business": "商业",
 "Business & Grants": "商业与资助",
 "Business type": "企业类型",
 "CHECKLIST": "清单",
 "Can I claim for a disabled child?": "残障子女可以申请减免吗？",
 "Cash aid": "现金援助",
 "Check Assistance": "福利检查",
 "Check Eligibility": "检查资格",
 "Check it yourself.": "亲自核实。",
 "Check with PERKESO": "向 PERKESO 查询",
 "Check your EPF statement is up to date": "确认您的 EPF 结算表为最新",
 "Chest": "胸部",
 "Civic & Education": "公民与教育",
 "Claim it when you file your income tax return on MyTax (e-Filing), under the child relief section.": "在 MyTax（e-Filing）申报所得税时，于子女减免一栏申请。",
 "Clear guidance, grounded in KKM advice.": "清晰指引，以 KKM 建议为依据。",
 "Closes 15 Jan 2027": "2027年1月15日截止",
 "Closes 30 Nov 2026": "2026年11月30日截止",
 "Commercialisation fund": "商业化基金",
 "Compliance Checklist": "合规清单",
 "Compliance Drafter": "合规起草代理",
 "Comply.": "合规。",
 "Confidence: 92%": "置信度：92%",
 "Confirm & Generate File": "确认并生成文件",
 "Confirm, and the file is ready.": "确认后，文件即可生成。",
 "Connect": "连接",
 "Consultancy": "咨询服务",
 "Continue": "继续",
 "Copied to clipboard": "已复制到剪贴板",
 "Copy": "复制",
 "Copy link": "复制链接",
 "Copy link, WhatsApp, Telegram, Facebook — or draft a caption with AI.": "复制链接、WhatsApp、Telegram、Facebook — 或用 AI 生成文案。",
 "Correct · 7": "正确 · 7",
 "Cough": "咳嗽",
 "Counts down for you": "为您倒数",
 "Cradle": "Cradle",
 "Cross-references LHDN, EPF/SOCSO/EIS, and SSM compliance obligations for your SME.": "为您的中小企业交叉核对 LHDN、EPF/SOCSO/EIS 及 SSM 的合规义务。",
 "DOCUMENT CHECKLIST": "文件清单",
 "Deadline Monitor": "截止日期监控",
 "Deadlines": "截止日期",
 "Deadlines that come to you.": "截止日期，主动提醒您。",
 "Deduct monthly PCB (MTD) for every employee": "为每位员工每月扣除 PCB（MTD）",
 "Demographics": "人口统计",
 "Dependent children": "受养子女",
 "Describe what happened, in one line.": "用一句话描述发生了什么。",
 "Describe your business like you'd tell a friend.": "像跟朋友聊天一样描述您的企业。",
 "Digital adoption grant": "数字化应用补助金",
 "Digital adoption grant (MDEC)": "数字化应用补助金（MDEC）",
 "Director's MyKad copy": "董事 MyKad 副本",
 "Dizziness": "头晕",
 "Do you already have a job offer from a Malaysian employer?": "您是否已获得马来西亚雇主的工作邀约？",
 "Document checklist, warnings, and official references.": "文件清单、注意事项及官方参考资料。",
 "Done": "已完成",
 "Download draft": "下载草稿",
 "Download summary (PDF)": "下载摘要（PDF）",
 "Draft Ready": "草稿已就绪",
 "Draft a caption (AI)": "生成文案（AI）",
 "Draft an executive summary, use-of-funds narrative, and document checklist for your selected grant.": "为您选定的补助金起草执行摘要、资金用途说明及文件清单。",
 "Draft application →": "起草申请 →",
 "Draft it": "起草申请",
 "Draft.": "起草。",
 "Drafting response…": "正在撰写回答…",
 "Drop in a past paper.": "放入一份往年试卷。",
 "Drop your past paper here": "将往年试卷拖放到这里",
 "EIS Claim Eligibility": "EIS 索赔资格",
 "EIS claim eligibility, statutory termination benefits, and a next-steps checklist.": "EIS 索赔资格、法定终止福利，以及后续步骤清单。",
 "EIS claim eligibility, termination benefits, next steps.": "EIS 索赔资格、终止福利、后续步骤。",
 "EIS claim — how long?": "EIS 索赔 — 要多久？",
 "EN": "EN",
 "EPF contribution": "EPF 缴款",
 "EPF contribution — 15th": "EPF 缴款 — 每月15日",
 "EPF withdrawal": "EPF 提款",
 "EPF withdrawal for a home": "提取 EPF 买房",
 "EPF, PERKESO, LHDN, Customs, SSM — with the official source.": "EPF、PERKESO、LHDN、关税局、SSM — 均附官方来源。",
 "EXECUTIVE SUMMARY": "执行摘要",
 "Each match says why you qualify, and links the official source.": "每项配对都说明您符合资格的原因，并附官方来源链接。",
 "Each number is a source you can open.": "每个编号都是可点开的来源。",
 "Earlier": "更早",
 "EdTech": "教育科技",
 "Education": "教育",
 "Emergencies come first": "紧急情况优先",
 "Employer's job offer letter": "雇主的聘用信",
 "Employment": "就业",
 "Employment Pass": "就业准证（Employment Pass）",
 "End card": "End card",
 "Enrol foreign workers with SOCSO": "为外籍员工登记 SOCSO",
 "Enter to send · Ctrl+Enter · Esc to clear": "按 Enter 发送 · Ctrl+Enter · Esc 清空",
 "Essentials credit": "必需品额度",
 "Estimated Statutory Termination Benefit": "法定终止福利估算",
 "Every claim is numbered.": "每项说法都有编号。",
 "Every claim, linked to its official source.": "每项说法，都链接到官方来源。",
 "Every filing date, in one calendar.": "所有申报日期，尽在一个日历。",
 "Every grant you qualify for, ranked.": "您符合资格的所有资助，按匹配度排列。",
 "Every obligation, in one checklist.": "所有义务，尽在一份清单。",
 "Every question, explained.": "每道题目，都有讲解。",
 "Every scheme you match, in one list.": "您符合的所有计划，尽在一个列表。",
 "Everything you asked, saved.": "您问过的一切，都已保存。",
 "Executive summary, use of funds, document checklist.": "执行摘要、资金用途、文件清单。",
 "Explain": "讲解",
 "Explanations": "讲解",
 "Explore AI Agents": "探索 AI 智能代理",
 "Export Format": "导出格式",
 "Extend My Visa": "延长签证",
 "Extract & explain": "提取并讲解",
 "FREE": "免费版",
 "FREE CIVIC TOOLS": "免费公共工具",
 "Fan-out across up to 13 domains, merged into one synthesis.": "跨多达 13 个领域并行检索，合并为一篇综合分析。",
 "Feeling unwell": "身体不适",
 "Fever": "发烧",
 "File the annual return on time": "按时提交年度申报表",
 "File your EIS claim with PERKESO": "向 PERKESO 提交 EIS 索赔",
 "Financial Projection · Template only — not real figures": "财务预测 · 仅供参考的模板，并非实际数字",
 "Find grants": "寻找资助",
 "Find.": "寻找。",
 "Fintech": "金融科技",
 "Five quick answers about your business.": "回答五个关于您企业的简单问题。",
 "Focus next:": "下一步重点：",
 "Follow-ups, history, and the right agent.": "后续问题、历史记录，以及合适的代理。",
 "Form": "表格",
 "Found one? Draft the application.": "找到了？马上起草申请。",
 "Free": "免费",
 "Free Text": "自由文本",
 "Free.": "免费。",
 "From match to application, reviewed by you.": "从配对到申请，全程由您把关。",
 "General": "一般",
 "Generate Draft": "生成草稿",
 "Generate checklist": "生成清单",
 "Generate quiz": "生成测验",
 "Get directions": "获取路线",
 "Get guidance": "获取指引",
 "Go deeper": "深入了解",
 "Google Calendar": "Google 日历",
 "Google or Microsoft, with alerts before each deadline.": "Google 或 Microsoft 日历，每个截止日期前都会提醒。",
 "Grant & Business Details": "补助金与企业详情",
 "Grant Draft": "补助金草稿",
 "Grant Draft Generator": "补助金草稿生成器",
 "Grant Finder": "资助查找代理",
 "Grant Finder matches your business to government grants.": "资助查找代理为您的企业配对政府资助。",
 "Grants I qualify for": "我符合资格的资助",
 "Grants, filings, deadlines — handled.": "资助、申报、截止日期 — 一手包办。",
 "Grounded in Malaysian government sources, not the open web.": "以马来西亚政府来源为依据，而非网上的随意资料。",
 "Grounded.": "有据可依。",
 "Guided.": "一步步引导。",
 "Hardware": "硬件",
 "Head": "头部",
 "Headache": "头痛",
 "Health Triage": "健康分诊代理",
 "Health Triage, Check Assistance, Retrenchment Navigator": "健康分诊代理、福利检查、裁员导航代理",
 "Help / FAQ": "帮助 / 常见问题",
 "Here's your visa type and document checklist.": "以下是您的签证类型与文件清单。",
 "History": "History",
 "Home": "首页",
 "Hook": "Hook",
 "Household": "家庭",
 "Household income (RM)": "家庭收入（RM）",
 "Household income and children within the STR bands": "家庭收入与子女人数符合 STR 级别",
 "How bad?": "有多严重？",
 "How do I claim child tax relief?": "如何申请子女税务减免？",
 "How do I register a company with SSM?": "如何向 SSM 注册公司？",
 "How long?": "持续多久？",
 "How to pay taxes": "怎样缴税",
 "I need more details": "我需要更多详情",
 "I worked 3 years, salary RM4,500, given 14 days notice": "我工作了3年，薪水RM4,500，获得14天通知期",
 "I worked 3 years, salary RM4,500, given 14 days notice…": "我工作了3年，薪水RM4,500，获得14天通知期……",
 "I'm from Mainland China, want to work in KL for 2 years": "我来自中国大陆，想在吉隆坡工作两年",
 "ILLUSTRATIVE DEMO DATA": "示范数据，仅供说明",
 "If you contributed to EIS, claim within 60 days": "如有缴纳 EIS，须在 60 天内提出索赔",
 "Immigration": "移民事务",
 "Immigration & Documents": "移民与证件",
 "Immigration Navigator": "移民导航代理",
 "In effect from 1 Jan 2024": "自 2024年1月1日 起生效",
 "In plain language, with quick replies.": "用浅白的语言，还有快捷回复。",
 "It asks what matters, one step at a time.": "它一步步询问关键信息。",
 "It searches before it speaks.": "先查资料，再回答。",
 "It suggests the specialised agent built for the job.": "它会推荐专为这项任务打造的代理。",
 "JPN": "JPN",
 "Jawapan: pengaruh pendidikan dan akhbar, serta kesan Perang Dunia Kedua. Kata kunci: kesedaran, penentangan.": "Jawapan: pengaruh pendidikan dan akhbar, serta kesan Perang Dunia Kedua. Kata kunci: kesedaran, penentangan.",
 "Just ask.": "直接问。",
 "KKM": "KKM",
 "KPM": "KPM",
 "KWSP": "KWSP",
 "KWSP — i-Akaun": "KWSP — i-Akaun",
 "Keep birth certificates and enrolment letters in case LHDN asks.": "请保存出生证明与入学信，以备 LHDN 查核。",
 "Keep company particulars up to date": "保持公司资料为最新",
 "Keep your child's birth certificate, plus proof of enrolment for any child in higher education. LHDN can ask for them for up to 7 years.": "请保存孩子的出生证明，以及就读高等教育子女的入学证明。LHDN 可在 7 年内要求查核。",
 "Kemerdekaan": "Kemerdekaan",
 "Klinik Kesihatan · 1.2 km": "Klinik Kesihatan · 1.2 km",
 "Klinik Kesihatan · 3.4 km": "Klinik Kesihatan · 3.4 km",
 "Knowledge base → analysis → drafting, live on screen.": "知识库 → 分析 → 撰写，实时呈现。",
 "LHDN": "LHDN",
 "LHDN Form E": "LHDN E 表格",
 "LHDN, EPF · SOCSO · EIS, and SSM — cross-referenced.": "LHDN、EPF · SOCSO · EIS 及 SSM — 交叉核对。",
 "LHDN, EPF/SOCSO/EIS and SSM obligations for your SME.": "您中小企业的 LHDN、EPF/SOCSO/EIS 及 SSM 义务。",
 "LLP": "LLP",
 "Latest audited accounts": "最新经审计账目",
 "Leave with the visa type and a checklist.": "带着签证类型和清单离开。",
 "Level": "级别",
 "Life happens.": "生活总有变数。",
 "Life moments": "人生时刻",
 "Link copied!": "链接已复制！",
 "Losing a job": "失去工作",
 "Lost MyKad": "遗失 MyKad",
 "MANAGED SERVICE": "托管服务",
 "MDEC": "MDEC",
 "MOF": "MOF",
 "Macam mana nak keluarkan KWSP untuk beli rumah?": "Macam mana nak keluarkan KWSP untuk beli rumah?",
 "Making ends meet": "应付生活开销",
 "Malaysian government.": "马来西亚政府的疑问。",
 "Manufacturing": "制造业",
 "Many agents are free; others cost 1–3 credits a run.": "许多代理免费；其他每次使用 1–3 点数。",
 "Marital Status": "婚姻状况",
 "Married": "已婚",
 "Match your business profile to Malaysian government grants — with scoring, near-miss detection, and a recommended application sequence.": "将您的企业资料与马来西亚政府资助配对 —— 提供评分、近乎符合资格检测，以及建议的申请顺序。",
 "Match your household profile to cost-of-living assistance schemes (Ihsan MADANI and similar).": "将您的家庭资料与生活成本援助计划（Ihsan MADANI 及类似计划）配对。",
 "Match your household to cost-of-living assistance schemes.": "将您的家庭与生活成本援助计划配对。",
 "Match your profile to government grants (MDEC, TEKUN, MARA…).": "匹配您的资料与政府资助（MDEC、TEKUN、MARA……）。",
 "Matching…": "匹配中…",
 "Matematik": "Matematik",
 "Microsoft Calendar": "Microsoft 日历",
 "Mode": "模式",
 "Monthly": "每月",
 "Months registered": "注册月数",
 "Moving here": "移居马来西亚",
 "MyTax — login": "MyTax — 登录",
 "NEARBY FACILITIES": "附近医疗机构",
 "NakTahu Agents": "NakTahu 智能代理",
 "Nasionalisme": "Nasionalisme",
 "Nausea / Vomiting": "恶心/呕吐",
 "Near-miss — close, but doesn't fully qualify yet ·": "接近符合 —— 接近但尚未完全符合资格 ·",
 "Near-miss: what you'd need": "接近符合：还需满足什么",
 "Never a mystery why.": "原因从不含糊。",
 "Never miss one": "绝不错过",
 "New": "新",
 "No": "否",
 "No account needed to read a shared answer.": "无需账户即可阅读分享的回答。",
 "No keywords, no forms.": "不用关键词，不用填表格。",
 "Not quite · 1": "不正确 · 1",
 "Not the paperwork.": "而不是文书工作。",
 "Nothing is generated until you approve the draft.": "在您批准草稿之前，不会生成任何文件。",
 "Notice Period Status": "通知期状态",
 "One click hands it to the Grant Draft Generator.": "一键交给补助金草稿生成器。",
 "One tap asks the next obvious question.": "一按即可问出下一个问题。",
 "Open Official Portal": "打开官方门户",
 "Open →": "打开 →",
 "Or just say it.": "或者直接说出来。",
 "Or use the form — headcount, revenue, recent events.": "或使用表格 — 员工人数、收入、近期事件。",
 "Our company, a Kuala Lumpur Sdn Bhd registered for 18 months, is applying to digitise its order-to-invoice workflow. The grant will fund cloud software, staff training and a small hardware refresh, cutting manual processing time and letting the team serve more SME customers across the Klang Valley. The project runs for 12 months with quarterly milestones reported to the agency.": "本公司是一家已注册 18 个月的吉隆坡 Sdn Bhd，现申请将订单至发票的工作流程数字化。补助金将用于云端软件、员工培训及小规模硬件更新，以缩短人工处理时间，让团队服务巴生谷更多中小企业客户。项目为期 12 个月，每季度向机构汇报里程碑进度。",
 "PCB (MTD) remittance": "PCB（MTD）汇缴",
 "PCB table 2026 (PDF)": "2026 PCB 扣税表（PDF）",
 "PDF": "PDF",
 "PERKESO": "PERKESO",
 "PRO — BUSINESS": "Pro — 商业版",
 "PTPTN education loan": "PTPTN 教育贷款",
 "PVIP": "PVIP",
 "Paperwork follows.": "文书随之而来。",
 "Partially correct · 2": "部分正确 · 2",
 "Passport photo": "护照照片",
 "Passport with enough validity": "有效期充足的护照",
 "Past papers, explained. Then tested.": "往年试卷，先讲解，再测验。",
 "Paste it, upload the PDF, or scan a photo.": "粘贴文字、上传 PDF，或扫描照片。",
 "Paste text": "粘贴文字",
 "PatuhiKu": "PatuhiKu 合规助手",
 "Pay monthly EIS contributions": "每月缴纳 EIS 缴款",
 "Pay per use — or not at all.": "按次付费 — 或完全免费。",
 "Pelepasan bergantung pada umur dan pengajian anak — sehingga RM8,000 setahun bagi setiap anak di pengajian tinggi, tertakluk kepada syarat semasa LHDN.": "Pelepasan bergantung pada umur dan pengajian anak — sehingga RM8,000 setahun bagi setiap anak di pengajian tinggi, tertakluk kepada syarat semasa LHDN.",
 "Pending": "待处理",
 "Perniagaan Terurus: we handle your compliance and grants.": "Perniagaan Terurus：合规与资助，我们为您处理。",
 "Persekutuan 1948": "Persekutuan 1948",
 "Pick PDF or Word, then generate.": "选择 PDF 或 Word，然后生成。",
 "Pick what you're trying to do.": "选择您想要做的事。",
 "Plain words, straight to an answer.": "用浅白的话，直接得到答案。",
 "Plus official references and a ready-to-send enquiry.": "还附官方参考资料和一封可直接发送的询问信。",
 "Plus the nearest facilities and directions.": "还有最近的医疗机构和路线。",
 "Pricing": "价格",
 "Private sector": "私人界",
 "Pro": "Pro",
 "Property Concierge": "房产礼宾",
 "QUERY HISTORY": "查询历史",
 "Query history · Pro": "查询历史 · Pro",
 "Query history, grouped by day.": "查询历史，按日期分组。",
 "Quiz": "测验",
 "Quotations from vendors": "供应商报价单",
 "RM 150,000 – RM 500,000": "RM 150,000 – RM 500,000",
 "RM 99/mo per workspace · up to 5 staff": "RM 99/月，每个工作区 · 最多 5 位员工",
 "Rather hand it all off?": "想全部交给别人处理？",
 "Real gov.my source — never invented": "真实的 gov.my 来源 — 绝不捏造",
 "Reason shown for every match": "每项配对都显示原因",
 "Recap": "Recap",
 "Recommended": "推荐",
 "Regenerate response": "重新生成回答",
 "Register a company with SSM": "向 SSM 注册公司",
 "Register new foreign workers for EPF contributions": "为新外籍员工登记 EPF 缴款",
 "Register to vote": "登记成为选民",
 "Regulatory deadline calendar with proactive alerts.": "具有主动提醒功能的监管截止日期日历。",
 "Relief depends on your child's age and studies — up to RM8,000 a year per child in higher education, subject to current LHDN conditions.": "减免额视孩子的年龄与学业而定——每名就读高等教育的孩子每年最高可获 RM8,000，须符合 LHDN 现行条件。",
 "Renew ePLKS": "续签 ePLKS",
 "Request your final payslip and EA form": "索取最后一份工资单和 EA 表格",
 "Research Synthesiser": "研究综合代理",
 "Retrenchment": "裁员",
 "Retrenchment Navigator": "裁员导航代理",
 "Review Draft": "审阅草稿",
 "Rolling applications": "滚动申请",
 "Routes you to the right agent": "为您转到合适的代理",
 "Run the business.": "专心经营业务。",
 "Run your business": "经营您的企业",
 "SME Corp": "SME Corp",
 "SOCSO & EIS contribution": "SOCSO 与 EIS 缴款",
 "SOCSO form which one": "SOCSO 要填哪个表格",
 "SPM": "SPM",
 "SPM sejarah past year": "SPM Sejarah 往年试卷",
 "SPO Enquiry Draft": "SPO 询问草稿",
 "SSM": "SSM",
 "SSM annual return due??": "SSM 年度申报几时截止？？",
 "SSM company profile": "SSM 公司资料",
 "SST return": "SST 申报",
 "SST threshold?": "SST 门槛多少？",
 "STPM": "STPM",
 "STR, SARA and more — with the agency that runs each one.": "STR、SARA 等 — 并注明负责的机构。",
 "Sains": "Sains",
 "Same answer, same sources — just in your language.": "同样的回答，同样的来源 — 只是换成您的语言。",
 "Scan photo": "扫描照片",
 "Score: 8/10": "得分：8/10",
 "Scored against your profile": "根据您的资料评分",
 "Sdn Bhd": "Sdn Bhd",
 "Searching knowledge base…": "正在搜索知识库…",
 "Sector": "领域",
 "Sector, business type, age, revenue, ownership.": "领域、企业类型、成立时间、收入、拥有权。",
 "Sejarah": "Sejarah",
 "Selangor": "雪兰莪",
 "Send a verified answer in one tap.": "一按即可发送经核实的回答。",
 "Send it to the calendar you already use.": "同步到您常用的日历。",
 "Services": "服务业",
 "Severe": "严重",
 "Share": "分享",
 "Share it where people actually talk.": "分享到大家真正在聊天的地方。",
 "Share to Facebook": "分享到 Facebook",
 "Share to Telegram": "分享到 Telegram",
 "Share to WhatsApp": "分享到 WhatsApp",
 "Share.": "分享。",
 "Shared answers always carry the official-source disclaimer.": "分享的回答始终附有官方来源免责声明。",
 "Shared from NakTahu AI. Verify important information against official sources.": "来自 NakTahu AI 的分享内容。重要信息请以官方来源为准。",
 "Simpan sijil kelahiran dan surat pendaftaran sekiranya LHDN meminta.": "Simpan sijil kelahiran dan surat pendaftaran sekiranya LHDN meminta.",
 "Sitting SPM": "备考 SPM",
 "Skin": "皮肤",
 "Soalan 1 · Nyatakan dua faktor kemunculan nasionalisme di Tanah Melayu.": "Soalan 1 · Nyatakan dua faktor kemunculan nasionalisme di Tanah Melayu.",
 "Soalan 2 · Apakah tujuan penubuhan Persekutuan Tanah Melayu 1948?": "Soalan 2 · Apakah tujuan penubuhan Persekutuan Tanah Melayu 1948?",
 "Soalan 3 · Terangkan peranan Suruhanjaya Reid.": "Soalan 3 · Terangkan peranan Suruhanjaya Reid.",
 "Software & cloud": "软件与云端",
 "Sole Proprietor": "独资经营",
 "Some agents use \"credits\" — each credit is RM5 and covers one full use of that agent. Business plans have no limit.": "部分代理需使用“点数” — 每点数为 RM5，可完整使用该代理一次。商业版无使用上限。",
 "Some questions need more than an answer.": "有些问题，需要的不只是一个答案。",
 "Speak in BM and your words become the question.": "用 BM 说出来，您的话就变成问题。",
 "Staff training": "员工培训",
 "Start": "开始",
 "Start Asking": "开始提问",
 "Start a Business": "创办企业",
 "Start on naktahu.my.": "从 naktahu.my 开始。",
 "Start with money on the table.": "先从可以拿到的资金开始。",
 "Startup": "初创公司",
 "State of Residence": "居住州属",
 "Status": "状态",
 "Stay compliant": "保持合规",
 "Step-by-step helpers for everyday government tasks — answers grounded in official sources, not guesses.": "为日常政府事务提供逐步指引 — 答案均以官方来源为依据，而非猜测。",
 "Stop searching.": "不必再搜索。",
 "Straight to the official portal": "直达官方门户",
 "Student": "学生",
 "Study Agent": "学习 Agent",
 "Study in Malaysia": "在马来西亚留学",
 "Subject": "科目",
 "Submit Form E by 31 March": "3月31日前提交 E 表格",
 "Submit MDAC": "提交 MDAC",
 "Suggested follow-ups": "建议的后续问题",
 "Suggested follow-ups keep you moving.": "建议的后续问题，让您继续深入。",
 "Sumbangan Asas Rahmah (SARA)": "Sumbangan Asas Rahmah (SARA)",
 "Sumbangan Tunai Rahmah (STR)": "Sumbangan Tunai Rahmah (STR)",
 "Switch the answer to Bahasa Malaysia…": "把答案切换成 Bahasa Malaysia……",
 "Symptom intake → KKM guidance → clinic or hospital.": "症状问诊 → KKM 指引 → 诊所或医院。",
 "Symptoms": "症状",
 "Sync to your calendar": "同步到您的日历",
 "Take the summary with you.": "把摘要带在身边。",
 "Tap through what you're feeling.": "点选您的不适症状。",
 "Tax & EPF": "税务与公积金",
 "Tech Sdn Bhd, 8 employees, started hiring foreign workers last month, annual revenue RM800k": "科技私人有限公司，8 名员工，上月开始聘请外籍员工，年收入 RM800k",
 "Technology": "科技",
 "Technology fund": "科技基金",
 "Tell it about your household.": "告诉它您的家庭状况。",
 "Tell me about your plans — where are you from, and how long will you stay?": "说说您的计划 — 您来自哪里？打算停留多久？",
 "Tenancy, strata and land-title answers, plus a shareable brief.": "租赁、分层地契与地契问题解答，另附可分享的简报。",
 "Termination benefit, notice period, and where EIS fits in.": "终止福利、通知期，以及 EIS 的作用。",
 "The answer streams in as it's written.": "回答边写边呈现。",
 "The big moments, made simpler.": "人生大事，变得更简单。",
 "The grant and your details carry over.": "资助与您的资料会自动带入。",
 "The right visa, and every document for it.": "合适的签证，以及所需的每份文件。",
 "Then test yourself.": "然后自我测验。",
 "Then, what to do next.": "然后，告诉您下一步怎么做。",
 "They see the answer and its sources.": "对方能看到回答及其来源。",
 "Tick them off as you go.": "逐项勾选完成。",
 "Title": "Title",
 "Today": "今天",
 "Topic ·": "主题 ·",
 "Translate answer": "翻译回答",
 "Triggered by: foreign workers": "触发原因：外籍员工",
 "Tuntut semasa mengisi borang cukai pendapatan di MyTax (e-Filing), di bahagian pelepasan anak.": "Tuntut semasa mengisi borang cukai pendapatan di MyTax (e-Filing), di bahagian pelepasan anak.",
 "Twelve specialists for the paperwork of life.": "十二位专家，帮您处理生活中的各种文书。",
 "Type your answer…": "输入您的答案…",
 "Type your question in plain words.": "用浅白的话输入您的问题。",
 "USE OF FUNDS": "资金用途",
 "Up to RM 100,000": "最高 RM 100,000",
 "Up to RM 50,000": "最高 RM 50,000",
 "Upload PDF": "上传 PDF",
 "Upload your SPM past paper — an explanation for every question.": "上传您的 SPM 试卷 — 每道题目都有讲解。",
 "Upload your SPM past paper — get an explanation for every question and see which topics to focus on.": "上传您的 SPM 试卷 — 获取每道题目的讲解，并了解应重点复习的主题。",
 "Verified 12 Sep 2026": "已于 2026年9月12日 核实",
 "Verify": "核实",
 "Verify.": "核实。",
 "View official source ↗": "查看官方来源 ↗",
 "Visit": "探访",
 "Voice input": "语音输入",
 "WALKTHROUGH": "功能导览",
 "WALKTHROUGH 01 · ASK ANYTHING": "功能导览 01 · 有问必答",
 "WALKTHROUGH 02 · RUN YOUR BUSINESS": "功能导览 02 · 经营您的企业",
 "WALKTHROUGH 03 · LIFE MOMENTS": "功能导览 03 · 人生时刻",
 "Warung Watch": "Warung Watch 排队观察",
 "We Handle Your Compliance & Grants": "合规与资助，我们为您处理",
 "What do you need to know today?": "今天您想了解什么？",
 "What documents do I need?": "我需要哪些文件？",
 "What you're owed, and what to do next.": "您应得的权益，以及下一步怎么做。",
 "What you're owed, worked out.": "您应得的权益，一算便知。",
 "When is the e-Filing deadline?": "e-Filing 截止日期是什么时候？",
 "When it took effect, how confident the match is, and the official page.": "生效日期、配对置信度，以及官方页面。",
 "Where do you feel it?": "哪里不舒服？",
 "Where to go, and how soon.": "该去哪里，要多快去。",
 "Which documents should I keep?": "我应该保存哪些文件？",
 "Why you qualify ·": "符合资格原因 ·",
 "With the topic it tests, so you know what to revise.": "并标明考查的主题，让您知道该复习什么。",
 "Work in Malaysia": "在马来西亚工作",
 "Work, study, visit, start a business, extend a visa…": "工作、留学、探访、创业、延长签证……",
 "Years of service, salary, notice given.": "服务年资、薪水、通知期。",
 "Yes": "是",
 "You have school-age children": "您有学龄子女",
 "You review every section first.": "每个部分都先由您审阅。",
 "You're already an STR household": "您已是 STR 受惠家庭",
 "Your language": "您的语言",
 "Your obligations, grouped by agency.": "您的义务，按机构分组。",
 "Your postcode (e.g. 50450)": "您的邮政编码（例如 50450）",
 "Your profile, matched and ranked.": "根据您的资料配对并排名。",
 "am I eligible for STR?": "我可以拿 STR 吗？",
 "blog: 10 reliefs you missed": "博客：你漏掉的 10 项扣税",
 "currentColor": "currentColor",
 "e-Filing (MyTax) guide": "e-Filing（MyTax）指南",
 "e-Filing guide (PDF, 84 pages)": "e-Filing 指南（PDF，84 页）",
 "e.g. 18": "例如 18",
 "e.g. 250000": "例如 250000",
 "e.g. Tech Sdn Bhd, 8 employees, started hiring foreign workers last month…": "例如：科技私人有限公司，8 名员工，上月开始聘请外籍员工……",
 "foreign worker EPF rules": "外劳 EPF 规定",
 "forum: child relief 2024??": "论坛：2024 孩子扣税？？",
 "grant FAQ — page 3 of 9": "资助常见问题 — 第 3/9 页",
 "grants_list_v7_FINAL.xlsx": "grants_list_v7_FINAL.xlsx",
 "hasil.gov.my": "hasil.gov.my",
 "hasil.gov.my — Tax relief": "hasil.gov.my — 税务减免",
 "klinik near me open now": "附近诊所 现在有开吗",
 "lost MyKad what to do": "MyKad 丢了怎么办",
 "naktahu.my": "naktahu.my",
 "needs 24 months registered": "需注册满 24 个月",
 "news: budget tax changes": "新闻：财案税务新变动",
 "of 7 done": "/ 7 项已完成",
 "retrenchment benefit calculator": "裁员赔偿 计算器",
 "thread: is it RM2k or RM8k?": "帖子：到底是 RM2k 还是 RM8k？",
 "work visa malaysia 2026": "马来西亚 工作签证 2026",
 "{agent}": "{agent}",
 "· View official source ↗": "· 查看官方来源 ↗",
 "— revise the Reid Commission.": "—— 复习李特制宪委员会。",
 "…or 中文, in one click.": "……或 English，一键切换。",
 "≈ RM 7,788": "≈ RM 7,788",
 "● Bilingual engine active": "● 双语引擎运作中",
 "● gov.my sources verified": "● 已核实 gov.my 来源",
 "✓ Connected": "✓ 已连接",
 "✦ This looks like a {agent} question": "✦ 这看起来像是关于{agent}的问题",
 "减免额视孩子的年龄与学业而定——每名就读高等教育的孩子每年最高可获RM8,000，须符合LHDN现行条件。": "减免额视孩子的年龄与学业而定——每名就读高等教育的孩子每年最高可获RM8,000，须符合LHDN现行条件。",
 "在MyTax（e-Filing）申报所得税时，于子女减免一栏申请。": "在MyTax（e-Filing）申报所得税时，于子女减免一栏申请。",
 "请保存出生证明与入学信，以备LHDN查核。": "请保存出生证明与入学信，以备LHDN查核。",
 "🇲🇾 Built for Malaysia": "🇲🇾 专为马来西亚打造",
 "🔒 naktahu.my/a/k7Q2mX": "🔒 naktahu.my/a/k7Q2mX",
 "🚨 Emergency? Call 999 now": "🚨 紧急情况？请立即拨打 999",
 "🟡 Moderate": "🟡 中等",
 "🟡 See a doctor within 24 hours": "🟡 请在 24 小时内就医",
 "🟢 Mild": "🟢 轻微"
};
