// Bahasa Malaysia on-screen copy — the source every other language is localized from.
// Wherever a string exists in the product, it is the product's own wording
// (apps/web/src/lib/i18n/index.tsx or components/landing/TypewriterQuery.tsx).
export const bm = {
  "hook.badge": "Dibuat untuk Malaysia",
  "hook.h0": "Penat google?",
  "hook.h1": "Tanya NakTahu.",
  "hook.prompt": "Syarat pengeluaran KWSP akaun 1",
  "logo.h0": "Tanya je.",
  "logo.h1": "Jawapan terus.",
  "f3.h0": "Bukan chatbot.",
  "f3.h1": "Enjin jawapan.",
  "f3.sub": "Dibina untuk soalan kerajaan Malaysia.",
  "f4.h0": "Jawapan berasas.",
  "f4.h1": "Sumber kerajaan.",
  "f4.sub": "Setiap fakta disertakan sitasi bernombor.",
  "f5.h0": "Dipercayai.",
  "f5.h1": "Disahkan.",
  "f5.h2": "Dijawab.",
  "f6.sub": "Terjemah jawapan dengan satu klik.",
  "f7.h0": "Cakap je.",
  "f7.h1": "Kami dengar.",
  "f7.sub": "Tanya dengan suara, tak perlu taip.",
  "f8.h0": "Kongsi jawapan",
  "f8.h1": "ke WhatsApp.",
  "f8.sub": "Pautan kekal dengan sitasi, sedia dikongsi.",
  "f9.h0": "12 ejen pakar.",
  "f9.h1": "Satu tempat.",
  "f9.sub": "Dari geran hingga imigresen.",
  "f10.h0": "Cari geran",
  "f10.h1": "yang anda layak.",
  "f10.sub": "Padanan geran kerajaan & dana permulaan.",
  "f11.h0": "Draf permohonan,",
  "f11.h1": "siap dijana.",
  "f11.sub": "PDF atau DOCX, sedia disunting.",
  "f12.h0": "Triaj kesihatan.",
  "f12.h1": "Percuma.",
  "f12.sub": "Klinik hari ini, hospital, atau rehat di rumah.",
  "f13.h0": "Visa & permit,",
  "f13.h1": "dipermudah.",
  "f13.sub": "Kerja, belajar, MDAC, ePLKS & lagi.",
  "f14.h0": "Ulang kaji",
  "f14.h1": "SPM & STPM.",
  "f14.sub": "Imbas soalan, dapat penerangan & kuiz.",
  "f15.h0": "Warung penuh?",
  "f15.h1": "Semak dulu.",
  "f15.sub": "Status sesak & harga, dilaporkan orang ramai.",
  "f16.h0": "Soal banyak.",
  "f16.h1": "Jawab tepat.",
  "f16.sub": "Pematuhan, tarikh akhir, hartanah & lagi.",
  "f17.h0": "API untuk",
  "f17.h1": "pembangun.",
  "f17.sub": "REST API & widget.js yang boleh dibenam.",
  "f18.h0": "Mula",
  "f18.h1": "percuma.",
  "end.tagline": "Tanya je. Jawapan terus.",
  "end.cta": "Mula bertanya — percuma →",
  "end.disclaimer": "Bukan nasihat rasmi kerajaan · naktahu.my",
  "load.s1": "Menyambung ke agensi rasmi",
  "load.s2": "Memuatkan indeks dokumen",
  "load.s3": "Menyediakan ejen AI",
  "load.s4": "Sedia",
  "chat.verified": "Sumber gov.my disahkan",
  "chat.step1": "Mencari dalam pangkalan data…",
  "chat.step2": "Menganalisis maklumat…",
  "chat.step3": "Menyusun jawapan…",
  "chat.q": "Bagaimana cara daftar SSM untuk perniagaan baru?",
  "chat.queue": "Jawapan sedang dijana… taip untuk beratur",
  "ans.text": "Perniagaan milikan tunggal dan perkongsian boleh didaftarkan secara dalam talian melalui portal EzBiz SSM.",
  "ans.cite1": "SSM · Pendaftaran Perniagaan",
  "ans.cite2": "SSM · Portal EzBiz",
  "ans.followLabel": "SOALAN SUSULAN YANG DICADANGKAN",
  "ans.follow1": "Kos pendaftaran?",
  "ans.follow2": "Daftar Sdn Bhd?",
  "ver.title": "Pendaftaran Perniagaan",
  "ver.org": "Suruhanjaya Syarikat Malaysia (SSM)",
  "ver.confidence": "Keyakinan",
  "ver.verified": "Disahkan 19 Sep 2026",
  "ver.viewSource": "Lihat sumber rasmi ↗",
  "ver.stamp": "DISAHKAN",
  "tr.notice": "Diterjemah oleh AI — mungkin tidak setepat jawapan asal.",
  "voice.text": "Macam mana nak renew pasport?",
  "voice.label": "INPUT SUARA",
  "share.copy": "Salin pautan",
  "share.wa": "Kongsi ke WhatsApp",
  "share.tg": "Kongsi ke Telegram",
  "share.fb": "Kongsi ke Facebook",
  "share.caption": "Jana kapsyen (AI)",
  "share.header": "DIKONGSI DARIPADA NAKTAHU AI",
  "share.cta": "Tanya NakTahu →",
  "share.disclaimer": "Dikongsi daripada NakTahu AI. Sahkan maklumat penting dengan sumber rasmi.",
  "hub.suggest": "Ini kelihatan seperti soalan untuk {agent}",
  "hub.open": "Buka →",
  "agent.grant-finder": "Pencari Geran",
  "agent.grant-draft-generator": "Penjana Draf Geran",
  "agent.health-triage": "Triaj Kesihatan",
  "agent.immigration-navigator": "Navigator Imigresen",
  "agent.study-agent": "Ejen Pelajaran",
  "agent.sme-compliance-navigator": "PatuhiKu",
  "agent.compliance-drafter": "Pengarang Pematuhan",
  "agent.retrenchment-navigator": "Navigator Pemberhentian Kerja",
  "agent.property-concierge": "Concierge Hartanah",
  "agent.welfare-eligibility": "Semak Bantuan",
  "agent.research-synthesiser": "Penyelidik Sintesis",
  "agent.deadline-monitor": "Pemantau Tarikh Akhir",
  "badge.free": "Percuma",
  "badge.credit1": "1 kredit",
  "badge.credit3": "3 kredit",
  "badge.student": "Pelajar",
  "badge.pro": "Pro",
  "badge.business": "Perniagaan",
  "grant.chipAI": "🤖 AI",
  "grant.chipFintech": "💳 Fintech",
  "grant.chipAgri": "🌾 Pertanian",
  "grant.chipMonths": "18 bulan",
  "grant.matching": "Memadankan…",
  "grant.count": "2 geran sepadan",
  "grant.matchLabel": "sepadan",
  "grant.apply": "Mohon sekarang →",
  "grant.draft": "Draf permohonan →",
  "grant.nearMiss": "Hampir layak — dekat, tetapi belum layak sepenuhnya",
  "draft.exec": "Ringkasan Eksekutif",
  "draft.funds": "Penggunaan Dana",
  "draft.checklist": "Senarai Semak Dokumen",
  "draft.item1": "Profil syarikat",
  "draft.item2": "Penyata kewangan",
  "draft.item3": "Pelan perniagaan",
  "triage.emergency": "Kecemasan? Hubungi 999 sekarang",
  "triage.symptomLabel": "SIMPTOM",
  "triage.s1": "Demam",
  "triage.s2": "Batuk",
  "triage.s3": "Sakit tekak",
  "triage.mild": "Ringan",
  "triage.moderate": "Sederhana",
  "triage.severe": "Teruk",
  "triage.result": "Sederhana — Lawati klinik hari ini",
  "triage.nearby": "Kemudahan Berdekatan",
  "triage.pdf": "Muat turun ringkasan (PDF)",
  "imm.step": "LANGKAH 1",
  "imm.prompt": "Apa yang anda ingin lakukan?",
  "imm.work": "Bekerja di Malaysia",
  "imm.study": "Belajar di Malaysia",
  "imm.visit": "Melawat",
  "imm.business": "Memulakan Perniagaan",
  "imm.extend": "Lanjutkan Visa",
  "imm.mdac": "Hantar MDAC",
  "imm.eplks": "Perbaharui ePLKS",
  "imm.pvip": "PVIP",
  "imm.result": "Berikut adalah jenis visa dan senarai semak dokumen anda.",
  "imm.row1": "Jenis visa & pas",
  "imm.row2": "Senarai semak dokumen",
  "imm.row3": "Amaran penting",
  "imm.portal": "Buka Portal Rasmi ↗",
  "study.paste": "Tampal teks",
  "study.pdf": "Muat naik PDF",
  "study.scan": "Imbas foto",
  "study.scanning": "Mengimbas foto…",
  "study.paperHeader": "BIOLOGI · TINGKATAN 4",
  "study.question": "Apakah fungsi mitokondria?",
  "study.answer": "Menghasilkan tenaga melalui respirasi sel",
  "study.quiz": "KUIZ",
  "study.correct": "Betul",
  "study.score": "Skor: 8/10",
  "warung.name": "Warung Pak Mat",
  "warung.check": "Semak Status",
  "warung.status": "Sederhana Sibuk",
  "warung.reports": "Berdasarkan 12 laporan",
  "warung.chart": "Trend harga — Nasi Lemak",
  "warung.nearby": "📍 Cari warung berdekatan",
  "more.patuhiProgress": "5 daripada 8 selesai",
  "more.patuhi1": "Daftar majikan PERKESO",
  "more.patuhi2": "Caruman KWSP pekerja",
  "more.patuhi3": "Borang E LHDN",
  "more.deadlineDoc": "Borang E · LHDN",
  "more.daysLeft": "hari lagi",
  "more.retrenchSub": "Anggaran faedah & kelayakan",
  "more.retrenchEis": "✓ Layak SIP PERKESO",
  "more.checklist": "Senarai semak",
  "more.propertyTier": "Bersedia — semua maklumat lengkap",
  "more.propertyShare": "Kongsi via WhatsApp",
  "api.usage": "PENGGUNAAN · 14 HARI",
  "price.freeName": "Percuma",
  "price.period": "/bulan",
  "price.freeNote": "25 soalan sehari — percuma, tiada kad kredit diperlukan",
  "price.proName": "Pro — Individu",
  "price.proNote": "Tanya sebanyak mana pun soalan, tiada had harian",
} as const;

export type CopyKey = keyof typeof bm;
export type Copy = Record<CopyKey, string>;
